postgres: &postgres
  adapter: postgresql
  min_messages: WARNING

development:
  <<: *postgres
  database: chai_development

test:
  <<: *postgres
  database: chai_test

production:
  <<: *postgres
  database: chai_production
